if(NOT DEFINED ENV{VCPKG_PATH})
  message(FATAL_ERROR "Please clone vcpkg and set the VCPKG_PATH environment variable")
endif()

if (WIN32)
  set(VCPKG_FEATURE_FLAGS versions)
  set(VCPKG_TARGET_TRIPLET x64-windows-static)
  set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_PATH}/scripts/buildsystems/vcpkg.cmake)
else()
  set(VCPKG_FEATURE_FLAGS versions)
  set(VCPKG_TARGET_TRIPLET x64-linux)
  set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_PATH}/scripts/buildsystems/vcpkg.cmake)
endif()
