name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y inotify-tools libxmu-dev libxi-dev libgl-dev
        sudo apt install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
        pip3 install pytest-xdist

    - name: Cache Vcpkg Packages
      uses: actions/cache@v2
      env:
        cache-name: cache-vcpkg
      with:
        path: |
          ${{github.workspace}}/vcpkg/
          ${{github.workspace}}/${{env.BUILD_TYPE}}/vcpkg_installed/
          !${{github.workspace}}/vcpkg/buildtrees
          !${{github.workspace}}/vcpkg/packages
          !${{github.workspace}}/vcpkg/downloads
        key: ${{runner.os}}-build-${{env.cache-name}}-${{hashFiles('**/vcpkg.json')}}

    - name: Setup Vcpkg
      working-directory: ${{github.workspace}}
      run: |
        if [ ! -d "${{github.workspace}}/vcpkg" ]; then
        git clone https://github.com/microsoft/vcpkg.git
        fi
        if [ ! -f "${{github.workspace}}/vcpkg/vcpkg" ]; then
        sh vcpkg/bootstrap-vcpkg.sh
        fi
      env:
        VCPKG_TARGET_TRIPLET: x64-linux

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        bash build.sh ${{env.BUILD_TYPE}}
        pip3 install -e ${{env.BUILD_TYPE}}
      env:
        VCPKG_PATH: ${{github.workspace}}/vcpkg

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/${{env.BUILD_TYPE}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

    - name: Run Python Tests
      working-directory: ${{github.workspace}}/scripts
      run: pytest -n 4

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: galproject-build
        path: |
          ${{github.workspace}}/${{env.BUILD_TYPE}}/galview
          ${{github.workspace}}/${{env.BUILD_TYPE}}/pygalfunc.so
          ${{github.workspace}}/${{env.BUILD_TYPE}}/CascadiaMono.ttf
          ${{github.workspace}}/${{env.BUILD_TYPE}}/*.glsl
          ${{github.workspace}}/${{env.BUILD_TYPE}}/setup.py
        retention-days: 2
