name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y inotify-tools libxmu-dev libxi-dev libgl-dev
        sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Cache Vcpkg Packages
      uses: actions/cache@v2
      env:
        cache-name: cache-vcpkg-packages
      with:
        path: ~/vcpkg
        key: ${{runner.os}}-build-${{env.cache-name}}-${{hashFiles('${{github.workspace}}/vcpkg.json')}}

    - name: Setup Vcpkg
      working-directory: ~/
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        sh vcpkg/bootstrap-vcpkg.sh
      env:
        VCPKG_TARGET_TRIPLET: x64-linux

    - name: Build
      working-directory: ${{github.workspace}}
      run: bash build.sh ${{env.BUILD_TYPE}}
      env:
        VCPKG_PATH: ~/vcpkg

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/${{env.BUILD_TYPE}}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
